# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'touch-o-matic-tabbed.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.serialPort = QtWidgets.QComboBox(self.groupBox)
        self.serialPort.setObjectName("serialPort")
        self.gridLayout.addWidget(self.serialPort, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.baudRateValue = QtWidgets.QSpinBox(self.groupBox)
        self.baudRateValue.setMaximum(115200)
        self.baudRateValue.setProperty("value", 115200)
        self.baudRateValue.setObjectName("baudRateValue")
        self.horizontalLayout.addWidget(self.baudRateValue)
        self.serialConnect = QtWidgets.QPushButton(self.groupBox)
        self.serialConnect.setObjectName("serialConnect")
        self.horizontalLayout.addWidget(self.serialConnect)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yIntervalValue = QtWidgets.QSpinBox(self.groupBox_2)
        self.yIntervalValue.setMaximum(3600)
        self.yIntervalValue.setProperty("value", 30)
        self.yIntervalValue.setObjectName("yIntervalValue")
        self.horizontalLayout_2.addWidget(self.yIntervalValue)
        self.yIntervalUnits = QtWidgets.QComboBox(self.groupBox_2)
        self.yIntervalUnits.setMaxVisibleItems(3)
        self.yIntervalUnits.setObjectName("yIntervalUnits")
        self.yIntervalUnits.addItem("")
        self.yIntervalUnits.addItem("")
        self.yIntervalUnits.addItem("")
        self.horizontalLayout_2.addWidget(self.yIntervalUnits)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yLengthValue = QtWidgets.QSpinBox(self.groupBox_2)
        self.yLengthValue.setMaximum(500)
        self.yLengthValue.setProperty("value", 200)
        self.yLengthValue.setObjectName("yLengthValue")
        self.horizontalLayout_4.addWidget(self.yLengthValue)
        self.yLengthUnits = QtWidgets.QComboBox(self.groupBox_2)
        self.yLengthUnits.setObjectName("yLengthUnits")
        self.yLengthUnits.addItem("")
        self.yLengthUnits.addItem("")
        self.horizontalLayout_4.addWidget(self.yLengthUnits)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.goHome = QtWidgets.QPushButton(self.groupBox_4)
        self.goHome.setEnabled(False)
        self.goHome.setObjectName("goHome")
        self.gridLayout_7.addWidget(self.goHome, 2, 0, 1, 1)
        self.stopScan = QtWidgets.QPushButton(self.groupBox_4)
        self.stopScan.setEnabled(False)
        self.stopScan.setObjectName("stopScan")
        self.gridLayout_7.addWidget(self.stopScan, 1, 0, 1, 1)
        self.setHome = QtWidgets.QPushButton(self.groupBox_4)
        self.setHome.setEnabled(False)
        self.setHome.setObjectName("setHome")
        self.gridLayout_7.addWidget(self.setHome, 3, 0, 1, 1)
        self.startScan = QtWidgets.QPushButton(self.groupBox_4)
        self.startScan.setEnabled(False)
        self.startScan.setObjectName("startScan")
        self.gridLayout_7.addWidget(self.startScan, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 4, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_7)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.yMinus = QtWidgets.QToolButton(self.groupBox_6)
        self.yMinus.setEnabled(False)
        self.yMinus.setObjectName("yMinus")
        self.gridLayout_8.addWidget(self.yMinus, 2, 1, 1, 1)
        self.yPlus = QtWidgets.QToolButton(self.groupBox_6)
        self.yPlus.setEnabled(False)
        self.yPlus.setIconSize(QtCore.QSize(16, 16))
        self.yPlus.setObjectName("yPlus")
        self.gridLayout_8.addWidget(self.yPlus, 0, 1, 1, 1)
        self.xPlus = QtWidgets.QToolButton(self.groupBox_6)
        self.xPlus.setEnabled(False)
        self.xPlus.setObjectName("xPlus")
        self.gridLayout_8.addWidget(self.xPlus, 1, 2, 1, 1)
        self.xMinus = QtWidgets.QToolButton(self.groupBox_6)
        self.xMinus.setEnabled(False)
        self.xMinus.setObjectName("xMinus")
        self.gridLayout_8.addWidget(self.xMinus, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.manualStepValue = QtWidgets.QSpinBox(self.groupBox_6)
        self.manualStepValue.setMaximum(50)
        self.manualStepValue.setProperty("value", 10)
        self.manualStepValue.setObjectName("manualStepValue")
        self.horizontalLayout_9.addWidget(self.manualStepValue)
        self.manualStepUnits = QtWidgets.QComboBox(self.groupBox_6)
        self.manualStepUnits.setObjectName("manualStepUnits")
        self.manualStepUnits.addItem("")
        self.manualStepUnits.addItem("")
        self.horizontalLayout_9.addWidget(self.manualStepUnits)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.useArrows = QtWidgets.QCheckBox(self.groupBox_6)
        self.useArrows.setObjectName("useArrows")
        self.verticalLayout_3.addWidget(self.useArrows)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 1, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 2, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.commandLog = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.commandLog.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.commandLog.setFont(font)
        self.commandLog.setReadOnly(True)
        self.commandLog.setObjectName("commandLog")
        self.horizontalLayout_7.addWidget(self.commandLog)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.emergencyStop = QtWidgets.QPushButton(self.centralwidget)
        self.emergencyStop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.emergencyStop.setFont(font)
        self.emergencyStop.setObjectName("emergencyStop")
        self.gridLayout_2.addWidget(self.emergencyStop, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Touch-O-Matic"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Serial Port:"))
        self.label_2.setText(_translate("MainWindow", "Baud Rate:"))
        self.serialConnect.setText(_translate("MainWindow", "Connect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Y Axis Configuration"))
        self.label_4.setText(_translate("MainWindow", "Scan Interval: "))
        self.yIntervalUnits.setCurrentText(_translate("MainWindow", "Seconds"))
        self.yIntervalUnits.setItemText(0, _translate("MainWindow", "Seconds"))
        self.yIntervalUnits.setItemText(1, _translate("MainWindow", "Minutes"))
        self.yIntervalUnits.setItemText(2, _translate("MainWindow", "Hours"))
        self.label_5.setText(_translate("MainWindow", "Scan Length:"))
        self.yLengthUnits.setItemText(0, _translate("MainWindow", "mm"))
        self.yLengthUnits.setItemText(1, _translate("MainWindow", "inches"))
        self.groupBox_3.setTitle(_translate("MainWindow", "X Axis Configuration"))
        self.label_3.setText(_translate("MainWindow", "//TODO"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Scan Controls"))
        self.goHome.setText(_translate("MainWindow", "Return Home"))
        self.stopScan.setText(_translate("MainWindow", "Stop Scanning"))
        self.setHome.setText(_translate("MainWindow", "Set Home"))
        self.startScan.setText(_translate("MainWindow", "Start Scanning"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Manual Controls"))
        self.yMinus.setText(_translate("MainWindow", "Y -"))
        self.yPlus.setText(_translate("MainWindow", "Y +"))
        self.xPlus.setText(_translate("MainWindow", "X +"))
        self.xMinus.setText(_translate("MainWindow", "X -"))
        self.label_6.setText(_translate("MainWindow", "Step:"))
        self.manualStepUnits.setItemText(0, _translate("MainWindow", "mm"))
        self.manualStepUnits.setItemText(1, _translate("MainWindow", "inches"))
        self.useArrows.setText(_translate("MainWindow", "Enable Arrow Keys"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Scan Status"))
        self.label_7.setText(_translate("MainWindow", "Scan Duration:"))
        self.label_8.setText(_translate("MainWindow", "00:00:00"))
        self.label_9.setText(_translate("MainWindow", "Passes Completed:"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Next Pass In:"))
        self.label_12.setText(_translate("MainWindow", "00:00:00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scan Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Free Draw"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Command Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Event Log"))
        self.emergencyStop.setText(_translate("MainWindow", "Emergency Stop"))

