# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'touch-o-matic.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.serialPort = QtWidgets.QComboBox(self.groupBox)
        self.serialPort.setObjectName("serialPort")
        self.gridLayout.addWidget(self.serialPort, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.baudRateValue = QtWidgets.QSpinBox(self.groupBox)
        self.baudRateValue.setMaximum(115200)
        self.baudRateValue.setProperty("value", 115200)
        self.baudRateValue.setObjectName("baudRateValue")
        self.horizontalLayout.addWidget(self.baudRateValue)
        self.serialConnect = QtWidgets.QPushButton(self.groupBox)
        self.serialConnect.setObjectName("serialConnect")
        self.horizontalLayout.addWidget(self.serialConnect)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yIntervalValue = QtWidgets.QSpinBox(self.groupBox_2)
        self.yIntervalValue.setMaximum(3600)
        self.yIntervalValue.setProperty("value", 30)
        self.yIntervalValue.setObjectName("yIntervalValue")
        self.horizontalLayout_2.addWidget(self.yIntervalValue)
        self.yIntervalUnits = QtWidgets.QComboBox(self.groupBox_2)
        self.yIntervalUnits.setMaxVisibleItems(3)
        self.yIntervalUnits.setObjectName("yIntervalUnits")
        self.yIntervalUnits.addItem("")
        self.yIntervalUnits.addItem("")
        self.yIntervalUnits.addItem("")
        self.horizontalLayout_2.addWidget(self.yIntervalUnits)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yLengthValue = QtWidgets.QSpinBox(self.groupBox_2)
        self.yLengthValue.setMaximum(200)
        self.yLengthValue.setProperty("value", 90)
        self.yLengthValue.setObjectName("yLengthValue")
        self.horizontalLayout_4.addWidget(self.yLengthValue)
        self.yLengthUnits = QtWidgets.QComboBox(self.groupBox_2)
        self.yLengthUnits.setObjectName("yLengthUnits")
        self.yLengthUnits.addItem("")
        self.yLengthUnits.addItem("")
        self.horizontalLayout_4.addWidget(self.yLengthUnits)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.emergencyStop = QtWidgets.QPushButton(self.centralwidget)
        self.emergencyStop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.emergencyStop.setFont(font)
        self.emergencyStop.setObjectName("emergencyStop")
        self.gridLayout_2.addWidget(self.emergencyStop, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.startScan = QtWidgets.QPushButton(self.groupBox_4)
        self.startScan.setEnabled(False)
        self.startScan.setObjectName("startScan")
        self.gridLayout_7.addWidget(self.startScan, 0, 0, 1, 1)
        self.goHome = QtWidgets.QPushButton(self.groupBox_4)
        self.goHome.setEnabled(False)
        self.goHome.setObjectName("goHome")
        self.gridLayout_7.addWidget(self.goHome, 2, 0, 1, 1)
        self.stopScan = QtWidgets.QPushButton(self.groupBox_4)
        self.stopScan.setEnabled(False)
        self.stopScan.setObjectName("stopScan")
        self.gridLayout_7.addWidget(self.stopScan, 1, 0, 1, 1)
        self.setHome = QtWidgets.QPushButton(self.groupBox_4)
        self.setHome.setEnabled(False)
        self.setHome.setObjectName("setHome")
        self.gridLayout_7.addWidget(self.setHome, 3, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.yMinus = QtWidgets.QToolButton(self.groupBox_4)
        self.yMinus.setEnabled(False)
        self.yMinus.setObjectName("yMinus")
        self.gridLayout_8.addWidget(self.yMinus, 2, 1, 1, 1)
        self.yPlus = QtWidgets.QToolButton(self.groupBox_4)
        self.yPlus.setEnabled(False)
        self.yPlus.setIconSize(QtCore.QSize(16, 16))
        self.yPlus.setObjectName("yPlus")
        self.gridLayout_8.addWidget(self.yPlus, 0, 1, 1, 1)
        self.xPlus = QtWidgets.QToolButton(self.groupBox_4)
        self.xPlus.setEnabled(False)
        self.xPlus.setObjectName("xPlus")
        self.gridLayout_8.addWidget(self.xPlus, 1, 2, 1, 1)
        self.xMinus = QtWidgets.QToolButton(self.groupBox_4)
        self.xMinus.setEnabled(False)
        self.xMinus.setObjectName("xMinus")
        self.gridLayout_8.addWidget(self.xMinus, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.useArrows = QtWidgets.QCheckBox(self.groupBox_4)
        self.useArrows.setObjectName("useArrows")
        self.verticalLayout_3.addWidget(self.useArrows)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.commandLog = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.commandLog.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.commandLog.setFont(font)
        self.commandLog.setReadOnly(True)
        self.commandLog.setObjectName("commandLog")
        self.horizontalLayout_7.addWidget(self.commandLog)
        self.gridLayout_2.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Touch-O-Matic"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Serial Port:"))
        self.label_2.setText(_translate("MainWindow", "Baud Rate:"))
        self.serialConnect.setText(_translate("MainWindow", "Connect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Y Axis Configuration"))
        self.label_4.setText(_translate("MainWindow", "Scan Interval: "))
        self.yIntervalUnits.setCurrentText(_translate("MainWindow", "Seconds"))
        self.yIntervalUnits.setItemText(0, _translate("MainWindow", "Seconds"))
        self.yIntervalUnits.setItemText(1, _translate("MainWindow", "Minutes"))
        self.yIntervalUnits.setItemText(2, _translate("MainWindow", "Hours"))
        self.label_5.setText(_translate("MainWindow", "Scan Length:"))
        self.yLengthUnits.setItemText(0, _translate("MainWindow", "mm"))
        self.yLengthUnits.setItemText(1, _translate("MainWindow", "inches"))
        self.groupBox_3.setTitle(_translate("MainWindow", "X Axis Configuration"))
        self.label_3.setText(_translate("MainWindow", "//TODO"))
        self.emergencyStop.setText(_translate("MainWindow", "Emergency Stop"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Machine Controls"))
        self.startScan.setText(_translate("MainWindow", "Start Scanning"))
        self.goHome.setText(_translate("MainWindow", "Return Home"))
        self.stopScan.setText(_translate("MainWindow", "Stop Scanning"))
        self.setHome.setText(_translate("MainWindow", "Set Home"))
        self.yMinus.setText(_translate("MainWindow", "Y -"))
        self.yPlus.setText(_translate("MainWindow", "Y +"))
        self.xPlus.setText(_translate("MainWindow", "X +"))
        self.xMinus.setText(_translate("MainWindow", "X -"))
        self.useArrows.setText(_translate("MainWindow", "Use Arrow Keys"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Command Log"))

