# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'touch-o-matic-tabbed.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.serialPort = QtWidgets.QComboBox(self.groupBox)
        self.serialPort.setObjectName("serialPort")
        self.gridLayout.addWidget(self.serialPort, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.baudRateValue = QtWidgets.QSpinBox(self.groupBox)
        self.baudRateValue.setMaximum(115200)
        self.baudRateValue.setProperty("value", 115200)
        self.baudRateValue.setObjectName("baudRateValue")
        self.horizontalLayout.addWidget(self.baudRateValue)
        self.serialConnect = QtWidgets.QPushButton(self.groupBox)
        self.serialConnect.setObjectName("serialConnect")
        self.horizontalLayout.addWidget(self.serialConnect)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 2, 1, 1)
        self.cncSelect = QtWidgets.QComboBox(self.groupBox)
        self.cncSelect.setObjectName("cncSelect")
        self.gridLayout.addWidget(self.cncSelect, 0, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.basicTab = QtWidgets.QWidget()
        self.basicTab.setObjectName("basicTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.basicTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.basicTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yIntervalValue = QtWidgets.QSpinBox(self.groupBox_2)
        self.yIntervalValue.setMaximum(3600)
        self.yIntervalValue.setProperty("value", 30)
        self.yIntervalValue.setObjectName("yIntervalValue")
        self.horizontalLayout_2.addWidget(self.yIntervalValue)
        self.yIntervalUnits = QtWidgets.QComboBox(self.groupBox_2)
        self.yIntervalUnits.setMaxVisibleItems(3)
        self.yIntervalUnits.setObjectName("yIntervalUnits")
        self.yIntervalUnits.addItem("")
        self.yIntervalUnits.addItem("")
        self.yIntervalUnits.addItem("")
        self.horizontalLayout_2.addWidget(self.yIntervalUnits)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yLengthValue = QtWidgets.QSpinBox(self.groupBox_2)
        self.yLengthValue.setMinimum(-1000)
        self.yLengthValue.setMaximum(1000)
        self.yLengthValue.setProperty("value", 0)
        self.yLengthValue.setObjectName("yLengthValue")
        self.horizontalLayout_4.addWidget(self.yLengthValue)
        self.primary_units = QtWidgets.QLabel(self.groupBox_2)
        self.primary_units.setText("")
        self.primary_units.setObjectName("primary_units")
        self.horizontalLayout_4.addWidget(self.primary_units)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.basicTab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.xLengthValue = QtWidgets.QSpinBox(self.groupBox_3)
        self.xLengthValue.setMinimum(-1000)
        self.xLengthValue.setMaximum(1000)
        self.xLengthValue.setProperty("value", 0)
        self.xLengthValue.setObjectName("xLengthValue")
        self.horizontalLayout_12.addWidget(self.xLengthValue)
        self.secondary_units = QtWidgets.QLabel(self.groupBox_3)
        self.secondary_units.setText("")
        self.secondary_units.setObjectName("secondary_units")
        self.horizontalLayout_12.addWidget(self.secondary_units)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.basicTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.goHome = QtWidgets.QPushButton(self.groupBox_4)
        self.goHome.setEnabled(False)
        self.goHome.setObjectName("goHome")
        self.gridLayout_7.addWidget(self.goHome, 2, 0, 1, 1)
        self.stopScan = QtWidgets.QPushButton(self.groupBox_4)
        self.stopScan.setEnabled(False)
        self.stopScan.setObjectName("stopScan")
        self.gridLayout_7.addWidget(self.stopScan, 1, 0, 1, 1)
        self.setHome = QtWidgets.QPushButton(self.groupBox_4)
        self.setHome.setEnabled(False)
        self.setHome.setObjectName("setHome")
        self.gridLayout_7.addWidget(self.setHome, 3, 0, 1, 1)
        self.startScan = QtWidgets.QPushButton(self.groupBox_4)
        self.startScan.setEnabled(False)
        self.startScan.setObjectName("startScan")
        self.gridLayout_7.addWidget(self.startScan, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_7)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.basicTab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.yMinus = QtWidgets.QToolButton(self.groupBox_6)
        self.yMinus.setEnabled(False)
        self.yMinus.setObjectName("yMinus")
        self.gridLayout_8.addWidget(self.yMinus, 2, 1, 1, 1)
        self.yPlus = QtWidgets.QToolButton(self.groupBox_6)
        self.yPlus.setEnabled(False)
        self.yPlus.setIconSize(QtCore.QSize(16, 16))
        self.yPlus.setObjectName("yPlus")
        self.gridLayout_8.addWidget(self.yPlus, 0, 1, 1, 1)
        self.xPlus = QtWidgets.QToolButton(self.groupBox_6)
        self.xPlus.setEnabled(False)
        self.xPlus.setObjectName("xPlus")
        self.gridLayout_8.addWidget(self.xPlus, 1, 2, 1, 1)
        self.xMinus = QtWidgets.QToolButton(self.groupBox_6)
        self.xMinus.setEnabled(False)
        self.xMinus.setObjectName("xMinus")
        self.gridLayout_8.addWidget(self.xMinus, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.manualStepValue = QtWidgets.QSpinBox(self.groupBox_6)
        self.manualStepValue.setMaximum(50)
        self.manualStepValue.setProperty("value", 10)
        self.manualStepValue.setObjectName("manualStepValue")
        self.horizontalLayout_9.addWidget(self.manualStepValue)
        self.manual_units = QtWidgets.QLabel(self.groupBox_6)
        self.manual_units.setText("")
        self.manual_units.setObjectName("manual_units")
        self.horizontalLayout_9.addWidget(self.manual_units)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.useArrows = QtWidgets.QCheckBox(self.groupBox_6)
        self.useArrows.setObjectName("useArrows")
        self.verticalLayout_3.addWidget(self.useArrows)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.basicTab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 1, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.basicTab, "")
        self.customTab = QtWidgets.QWidget()
        self.customTab.setObjectName("customTab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.customTab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.saveCustom = QtWidgets.QToolButton(self.customTab)
        self.saveCustom.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/icons8-save-filled-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveCustom.setIcon(icon)
        self.saveCustom.setIconSize(QtCore.QSize(24, 24))
        self.saveCustom.setObjectName("saveCustom")
        self.gridLayout_13.addWidget(self.saveCustom, 0, 0, 1, 1)
        self.loadCustom = QtWidgets.QToolButton(self.customTab)
        self.loadCustom.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/icons8-opened-folder-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadCustom.setIcon(icon1)
        self.loadCustom.setIconSize(QtCore.QSize(24, 24))
        self.loadCustom.setObjectName("loadCustom")
        self.gridLayout_13.addWidget(self.loadCustom, 1, 0, 1, 1)
        self.horizontalLayout_13.addLayout(self.gridLayout_13)
        self.line_4 = QtWidgets.QFrame(self.customTab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_13.addWidget(self.line_4)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.rotateL = QtWidgets.QToolButton(self.customTab)
        self.rotateL.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/icons8-rotate-right-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateL.setIcon(icon2)
        self.rotateL.setIconSize(QtCore.QSize(24, 24))
        self.rotateL.setObjectName("rotateL")
        self.gridLayout_10.addWidget(self.rotateL, 2, 1, 1, 1)
        self.zoomInButton = QtWidgets.QToolButton(self.customTab)
        self.zoomInButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/icons8-plus-math-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInButton.setIcon(icon3)
        self.zoomInButton.setIconSize(QtCore.QSize(24, 24))
        self.zoomInButton.setObjectName("zoomInButton")
        self.gridLayout_10.addWidget(self.zoomInButton, 1, 1, 1, 1)
        self.rotateR = QtWidgets.QToolButton(self.customTab)
        self.rotateR.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/icons8-rotate-left-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateR.setIcon(icon4)
        self.rotateR.setIconSize(QtCore.QSize(24, 24))
        self.rotateR.setObjectName("rotateR")
        self.gridLayout_10.addWidget(self.rotateR, 2, 2, 1, 1)
        self.zoomOutButton = QtWidgets.QToolButton(self.customTab)
        self.zoomOutButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Assets/icons8-subtract-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutButton.setIcon(icon5)
        self.zoomOutButton.setIconSize(QtCore.QSize(24, 24))
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.gridLayout_10.addWidget(self.zoomOutButton, 1, 2, 1, 1)
        self.horizontalLayout_13.addLayout(self.gridLayout_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.waypointLabel = QtWidgets.QLabel(self.customTab)
        self.waypointLabel.setObjectName("waypointLabel")
        self.verticalLayout_5.addWidget(self.waypointLabel)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_13 = QtWidgets.QLabel(self.customTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.customTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_11)
        self.line_2 = QtWidgets.QFrame(self.customTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.label_14 = QtWidgets.QLabel(self.customTab)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.customIntervalValue = QtWidgets.QSpinBox(self.customTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customIntervalValue.sizePolicy().hasHeightForWidth())
        self.customIntervalValue.setSizePolicy(sizePolicy)
        self.customIntervalValue.setMaximum(3600)
        self.customIntervalValue.setProperty("value", 30)
        self.customIntervalValue.setObjectName("customIntervalValue")
        self.gridLayout_12.addWidget(self.customIntervalValue, 0, 0, 1, 1)
        self.customIntervalUnits = QtWidgets.QComboBox(self.customTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customIntervalUnits.sizePolicy().hasHeightForWidth())
        self.customIntervalUnits.setSizePolicy(sizePolicy)
        self.customIntervalUnits.setEditable(False)
        self.customIntervalUnits.setObjectName("customIntervalUnits")
        self.customIntervalUnits.addItem("")
        self.customIntervalUnits.addItem("")
        self.customIntervalUnits.addItem("")
        self.gridLayout_12.addWidget(self.customIntervalUnits, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_12)
        self.line_3 = QtWidgets.QFrame(self.customTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.startCustom = QtWidgets.QPushButton(self.customTab)
        self.startCustom.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startCustom.sizePolicy().hasHeightForWidth())
        self.startCustom.setSizePolicy(sizePolicy)
        self.startCustom.setObjectName("startCustom")
        self.verticalLayout_5.addWidget(self.startCustom)
        self.stopCustom = QtWidgets.QPushButton(self.customTab)
        self.stopCustom.setEnabled(False)
        self.stopCustom.setObjectName("stopCustom")
        self.verticalLayout_5.addWidget(self.stopCustom)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.customTab, "")
        self.eventTab = QtWidgets.QWidget()
        self.eventTab.setObjectName("eventTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.eventTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.eventTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.commandLog = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.commandLog.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.commandLog.setFont(font)
        self.commandLog.setReadOnly(True)
        self.commandLog.setObjectName("commandLog")
        self.horizontalLayout_7.addWidget(self.commandLog)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.eventTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.emergencyStop = QtWidgets.QPushButton(self.centralwidget)
        self.emergencyStop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.emergencyStop.setFont(font)
        self.emergencyStop.setObjectName("emergencyStop")
        self.gridLayout_2.addWidget(self.emergencyStop, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Basic_Scan = QtWidgets.QAction(MainWindow)
        self.actionLoad_Basic_Scan.setObjectName("actionLoad_Basic_Scan")
        self.actionSave_Basic_Scan = QtWidgets.QAction(MainWindow)
        self.actionSave_Basic_Scan.setObjectName("actionSave_Basic_Scan")
        self.actionLoad_Custom_Scan = QtWidgets.QAction(MainWindow)
        self.actionLoad_Custom_Scan.setObjectName("actionLoad_Custom_Scan")
        self.actionSave_Custom_Scan = QtWidgets.QAction(MainWindow)
        self.actionSave_Custom_Scan.setObjectName("actionSave_Custom_Scan")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Touch-O-Matic"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Serial Port:"))
        self.label_2.setText(_translate("MainWindow", "Baud Rate:"))
        self.serialConnect.setText(_translate("MainWindow", "Connect"))
        self.label_12.setText(_translate("MainWindow", "CNC Machine:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Primary Axis Configuration"))
        self.label_4.setText(_translate("MainWindow", "Scan Interval: "))
        self.yIntervalUnits.setCurrentText(_translate("MainWindow", "Seconds"))
        self.yIntervalUnits.setItemText(0, _translate("MainWindow", "Seconds"))
        self.yIntervalUnits.setItemText(1, _translate("MainWindow", "Minutes"))
        self.yIntervalUnits.setItemText(2, _translate("MainWindow", "Hours"))
        self.label_5.setText(_translate("MainWindow", "Scan Length:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Secondary Axis Configuration"))
        self.label_16.setText(_translate("MainWindow", "Position:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Scan Controls"))
        self.goHome.setText(_translate("MainWindow", "Return Home"))
        self.stopScan.setText(_translate("MainWindow", "Stop Scanning"))
        self.setHome.setText(_translate("MainWindow", "Set Home"))
        self.startScan.setText(_translate("MainWindow", "Start Scanning"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Manual Controls"))
        self.yMinus.setText(_translate("MainWindow", "Y -"))
        self.yPlus.setText(_translate("MainWindow", "Y +"))
        self.xPlus.setText(_translate("MainWindow", "X +"))
        self.xMinus.setText(_translate("MainWindow", "X -"))
        self.label_6.setText(_translate("MainWindow", "Step:"))
        self.useArrows.setText(_translate("MainWindow", "Enable Arrow Keys"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Scan Status"))
        self.label_7.setText(_translate("MainWindow", "Scan Duration:"))
        self.label_8.setText(_translate("MainWindow", "00:00:00"))
        self.label_9.setText(_translate("MainWindow", "Passes Completed:"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basicTab), _translate("MainWindow", "Basic Scan"))
        self.saveCustom.setToolTip(_translate("MainWindow", "Save Route"))
        self.loadCustom.setToolTip(_translate("MainWindow", "Load Route"))
        self.rotateL.setToolTip(_translate("MainWindow", "Rotate Clockwise"))
        self.zoomInButton.setToolTip(_translate("MainWindow", "Zoom In"))
        self.rotateR.setToolTip(_translate("MainWindow", "Rotate Counter-clockwise"))
        self.zoomOutButton.setToolTip(_translate("MainWindow", "Zoom Out"))
        self.waypointLabel.setText(_translate("MainWindow", "Waypoint --"))
        self.label_13.setText(_translate("MainWindow", "Action:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Take Picture"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Run Script"))
        self.label_14.setText(_translate("MainWindow", "Interval:"))
        self.customIntervalUnits.setItemText(0, _translate("MainWindow", "Seconds"))
        self.customIntervalUnits.setItemText(1, _translate("MainWindow", "Minutes"))
        self.customIntervalUnits.setItemText(2, _translate("MainWindow", "Hours"))
        self.startCustom.setText(_translate("MainWindow", "Start Scan"))
        self.stopCustom.setText(_translate("MainWindow", "Stop Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.customTab), _translate("MainWindow", "Custom Scan"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Command Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eventTab), _translate("MainWindow", "Event Log"))
        self.emergencyStop.setText(_translate("MainWindow", "Emergency Stop"))
        self.actionLoad_Basic_Scan.setText(_translate("MainWindow", "Load Basic Scan"))
        self.actionSave_Basic_Scan.setText(_translate("MainWindow", "Save Basic Scan"))
        self.actionLoad_Custom_Scan.setText(_translate("MainWindow", "Load Custom Scan"))
        self.actionSave_Custom_Scan.setText(_translate("MainWindow", "Save Custom Scan"))

