name: ABCD
units: mm
default: true
primary-axis: y
dimensions:
  x-axis: 200
  y-axis: -800 
  z-axis: null
  grid-size: 50

instructions:
  # connect to the machine
  connect: \r\n\r\n
  # run before every scan
  prefix: G21
  # run after every scan
  postfix: null
  # move to an absolute position
  absolute:
    all: G90 GO  X{x} Y{y} Z{z}
    xy: G90 GO X{x} Y{y}
    x: G90 GO X{x}
    y: G90 GO Y{y}
    z: G90 GO Z{z}
  # move relative to current position
  relative:
    all: G91 GO  X{x} Y{y} Z{z}
    x: G91 GO X{x}
    y: G91 GO Y{y}
    z: G91 GO Z{x}
  # stop in the middle of movement
  stop: "!"
