name: ABCD
units: mm
units-scale: 10 #convert to cm
default: true
primary-axis: y
dimensions:
  x-axis: 720
  y-axis: 1640
  z-axis: null
  grid-size: 100

# set the correct machine scale
scale:
  x: "$100 = 39.56"
  y: "$101 = 39.36"
  z: "$102 = 39.36"
# invert axes
invert:
  x: "$3 = 3"
  y: "$3 = 3"

default-speed: 6000 #mm/minute
speed-scale: 600 # convert to cm/s

instructions:
  # connect to the machine
  connect: \r\n\r\nG21 G17 G01\r\n
  # run after every scan
  postfix: null
  # move to an absolute position
  absolute:
    xyz: G90 X{x} Y{y} Z{z}
    xy: G90 X{x} Y{y}
    x: G90 X{x}
    y: G90 Y{y}
    z: G90 Z{z}
  # move relative to current position
  relative:
    xyz: G91 X{x} Y{y} Z{z}
    x: G91 X{x}
    y: G91 Y{y}
    z: G91 Z{x}
  # set current position as home
  set-home: G10 P0 L20 X0 Y0 Z0
  # get position info
  info:
    command: "?"
    regex: WPos:(-?[0-9]+\.?[0-9]*),(-?[0-9]+\.?[0-9]*),(-?[0-9]+\.?[0-9]*)
    order: xyz
  # stop in the middle of movement
  stop: "!~"
  # don't move for t seconds
  wait: G04 X{t}
  # set velocity in all 3 axes to s
  set-speed: "$110 = {v}\r\n$111 = {v}\r\n$112 = {v}"
